version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: creole-creamery-hall-of-fame-db
    environment:
      POSTGRES_DB: creole_creamery_hof
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d creole_creamery_hof"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
